steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/calculator:$BRANCH_NAME-$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/calculator:latest', '.' ]
# push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/calculator"]
- name: 'gcr.io/$PROJECT_ID/helm'
  args: ['upgrade', '--install', 'calculator', '--namespace', 'default', 'stable/calculator']
  env:
  - 'CLOUDSDK_COMPUTE_REGION=europe-west1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  
  - 'TILLERLESS=true'
  - 'TILLER_NAMESPACE=test'   
images:
- 'gcr.io/$PROJECT_ID/calculator'
