steps:
  # run unit tests
  - id: unit-tests
    name: "python:3.7-slim"
    entrypoint: /bin/sh
    args:
      - -c
      - "pip install -r requirements.txt && flake8 --statistics && python -m pytest -v"
# sonarqube code quality
  - id: code-quality
    name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    args:
    - '-Dsonar.host.url=http://http://35.201.70.180'
    - '-Dsonar.login=4b1713add8d8b000cc23123e4ee8697b4bc75b4b'
    - '-Dsonar.projectKey=python-example'
    - '-Dsonar.sources=.'      
  # build the container image
  - id: docker-build
    name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/calculator:$BRANCH_NAME-$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/calculator:latest",
        ".",
      ]
  # push container image
  - id: docker-push
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/calculator"]
  # deploy helm charts
  - id: helm-deploy
    name: "gcr.io/$PROJECT_ID/helm"
    args:
      [
        "upgrade",
        "--install",
        "calculator",
        "--namespace",
        "default",
        "./calculator",
        "--set",
        "image.repository=gcr.io/$PROJECT_ID/calculator",
        "--set",
        "image.tag=$BRANCH_NAME-$COMMIT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_REGION=europe-west1"
      - "CLOUDSDK_CONTAINER_CLUSTER=cluster-1"
      - "TILLERLESS=true"
      - "TILLER_NAMESPACE=test"
images:
  - "gcr.io/$PROJECT_ID/calculator"
