steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/calculator', '.' ]
# push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/calculator"]  
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/calculator', 'my-container=gcr.io/$PROJECT_ID/calculator']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'  
images:
- 'gcr.io/$PROJECT_ID/calculator'
